export enum ActionType {
  LOG_IN = 'LOG_IN',
  LOG_OUT = 'LOG_OUT',
  SET_LOADING_ON = 'SET_LOADING_ON',
  SET_LOADING_OFF = 'SET_LOADING_OFF',
  LOG_IN_SUCCESS = 'LOGGING_SUCCESS',
  LOG_IN_FAILED = 'LOGGING_FAILED',
}
